---
  # using vagrant to deploy VirtualBox vm on physical machine

# copy Vagrantfile
- hosts: vm_hosts
  remote_user: "{{ hostUser }}"
  vars_files:
    - vars.yml
  tasks:
  - name: create dest dir
    file:
      path: "{{ vmRootDir }}/{{ vmDirName }}/{{ vmSyncDirOnHost }}"
      state: directory
      mode: "0775"
  - name: put Vagrantfile to target machine with target dir
    template:
      src: "./template/Vagrantfile.j2.rb"
      dest: "{{ vmRootDir }}/{{ vmDirName }}/Vagrantfile"
      owner: "{{ hostUser }}"
      mode: u=rw,g=r,o=r
  - name: vagrant up
    shell: "vagrant up"
    args:
      chdir: "{{ vmRootDir }}/{{ vmDirName }}"
